<input type="hidden" id="idLyrics" value="<?php echo $this->lyrics[0]['lyr_id']?>">

<div class="row-fluid">
	<div class="span3 well text-center">
		<?php echo $this->partial('lyrics/sidebar_fiche.phtml', array(
		    'lyrics' => $this->lyrics[0],
		    'listeLyricsArtiste' => $this->listeLyricsArtiste,
			'identity' => $this->identity)); ?>
	</div>
    <div class="span7 text-center">
	    	<div class="video">
	    		<h1 class="h1-lyrics"><span class="text-head"><?php echo $this->lyrics[0]['lyr_title']?></span> | <?php echo $this->lyrics[0]['art_name']?></h1>
    			<iframe width="560" height="315" src="//www.youtube.com/embed/<?php echo $this->lyrics[0]['lyr_youtube']?>" frameborder="0"></iframe>
	    	</div>
	    	<div>
	    		<div class="well">
	    			<div class="text-rate">Avez-vous aimé cette traduction ?</div>
		    		<div class="btn-group">
			    		<a href="#" role="button" class="btn btn-success setThumbUp"><i class="icon-thumbs-up icon-white"></i></a>
			    		<button class="btn btn-inverse" type="button"><?php echo $this->lyrics[0]['lyr_up']?></button>
		  			</div>
		  			
		  			<div class="btn-group">
			    		<a href="#" role="button" class="btn btn-danger setThumbDown"><i class="icon-thumbs-down icon-white"></i></a>
			    		<button class="btn btn-inverse" type="button"><?php echo $this->lyrics[0]['lyr_down']?></button>
		  			</div>
		  			<?php if(!$this->identity): ?>
			  			<hr/>
			  			<div class="muted ">Vous pouvez modifier ou compléter cette traduction si vous êtes membre du site. <a href="#signInModal" data-toggle="modal">Connexion</a> | <a href="#signUpModal" data-toggle="modal">Inscription</a></div>
	  				<?php endif;?>
	  			</div>
	  			
	    		<?php foreach($this->lyrics as $line):?>
	    			<?php $texte = preg_replace('#\[(.+)\]#i', '<br/><strong>[$1]</strong>', $line['tra_line']);?>
	    			<div><?php echo $texte?></div>
	    			<?php if(!empty($line['tra_translate'])):?>
	    				<span class="label label-warning"><?php echo $line['tra_translate']?></span>
	    			<?php endif;?>
	    		<?php endforeach;?>
	    	</div>
    </div>
    <div class="span2">
		<?php echo $this->partial('lyrics/sidebar_ad.phtml'); ?>
	</div>
    	
</div>

<div class="row-fluid text-center block-btn-comment hide">
	<a href="<?php echo $this->url(array('controller'=>'lyrics', 'action'=>'add'),'default',true) ?>" role="button" class="btn btn-warning btn-large btn-comment" ><strong>Commenter</strong></a>
</div>
