<div class="row-fluid">
	<div class="span3 well text-center">
			<?php echo $this->partial('lyrics/sidebar_fiche.phtml', array(
		    'lyrics' => $this->lyrics[0],
		    'listeLyricsArtiste' => $this->listeLyricsArtiste)); ?>
	</div>
    <div class="span7 text-center">
	    	<div class="video">
	    		<h1 class="h1-lyrics"><span class="text-head"><?php echo $this->lyrics[0]['lyr_title']?></span> | <?php echo $this->lyrics[0]['art_name']?></h1>
    			<iframe width="560" height="315" src="//www.youtube.com/embed/<?php echo $this->lyrics[0]['lyr_youtube']?>" frameborder="0"></iframe>
	    	</div>
	    	
	    	<div>
				<div class="well">
				Traduisez chaque ligne des paroles de la musique. Laissez le champ vide si vous ne pouvez pas traduire une phrase.
				</div>
	    		<form action="<?php echo $this->url(array('controller'=>'lyrics', 'action'=>'translate'),'default',true) ?>" name="formTranslate" method="post">
	    		<div class="btn-valider-translate-up">
			      <button type="submit" class="btn btn-warning btn-large">Valider</button>
			    </div>
	    		<input type="hidden" value="<?php echo $this->lyrics[0]['lyr_id']?>" name="id" id="id">
	    		<?php foreach($this->lyrics as $line):?>
	    			<?php $texte = preg_replace('#\[(.+)\]#i', '<br/><strong>[$1]</strong>', $line['tra_line']);?>
	    			<div><?php echo $texte?></div>
	    			<?php if(!preg_match('#\[(.+)\]#i', $line['tra_line'])): ?>
	    				<div><input value="<?php echo $line['tra_translate']?>" type="text" class="input-xxlarge" name="translate[<?php echo $line['tra_id']?>]"></div>
	    			<?php endif;?>
	    		<?php endforeach;?>
	    		<div class="btn-valider-translate-down">
			      <button type="submit" class="btn btn-warning btn-large">Valider</button>
			    </div>
	    		</form>
	    	</div>
    </div>
    <div class="span2">
		<?php echo $this->partial('lyrics/sidebar_ad.phtml'); ?>
	</div>
    	
</div>

<div class="row-fluid text-center block-btn-comment hide">
	<input type="hidden" id="idLyrics" value="<?php echo $this->lyrics[0]['lyr_id']?>">
	<a href="<?php echo $this->url(array('controller'=>'lyrics', 'action'=>'add'),'default',true) ?>" role="button" class="btn btn-warning btn-large btn-comment" ><strong>Commenter</strong></a>
</div>
