<div id="signInModal" class="modal hide fade">
<form id="formSignInModal" class="form-horizontal" method="post" action="<?php echo $this->url(array('controller'=>'user', 'action'=>'sign-in'),'connexion',true) ?>">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Connexion</h3>
  </div>
  <div class="modal-body">
      <div class="control-group">
	    <label class="control-label" for="inputLogin">Email <span class="text-error">*</span></label>
	    <div class="controls">
	      <input type="text" id="email" name="email" placeholder="Email" required>
	    </div>
	  </div>
	  <div class="control-group">
	    <label class="control-label" for="inputPassword">Mot De Passe <span class="text-error">*</span></label>
	    <div class="controls">
	      <input type="password" id="password" name="password" placeholder="Mot De Passe" required>
	    </div>
	  </div>
  </div>
  <div class="modal-footer">
    <a href="#signUpModal" role="button" class="btn btn-inverse pull-left" data-toggle="modal" data-dismiss="modal" aria-hidden="true">Inscription</a>
    <a href="#" class="btn" data-dismiss="modal" aria-hidden="true">Fermer</a>
    <button type="submit" class="btn btn-warning">Se Connecter</button>
  </div>
</form>
</div>

<script>
	
	$("#formSignInModal").validate({
	      rules: {
	         "email":{
	            "required": true,
	            "email": true
	         },
	         "password":{
		        "required": true,
			 }
	      }
	  });
	  
</script>
