<div class="alert alert-error <?php echo ($this->unok) ? show : hide ?>">
	<button type="button" class="close" data-dismiss="alert">&times;</button>
	<strong>Oups!</strong> Problème d'identification. Si vous n'avez pas de compte <a href="#signUpModal" data-toggle="modal">inscrivez-vous</a>
</div>

<form id="formSignIn" class="form-horizontal" method="POST" action="<?php echo $this->url(array('controller'=>'user', 'action'=>'sign-in'),'default',true) ?>">
      <div class="control-group">
	    <label class="control-label">Email <span class="text-error">*</span></label>
	    <div class="controls">
	      <input type="text" name="email" id="email" placeholder="Email" required>
	    </div>
	  </div>
	  <div class="control-group">
	    <label class="control-label">Password <span class="text-error">*</span></label>
	    <div class="controls">
	      <input type="password" name="password" id="password" placeholder="Password" required>
	    </div>
	  </div>
	  <div class="control-group">
	    <div class="controls">
	      <button type="submit" class="btn btn-warning btn-large">Connexion</button>
	    </div>
	  </div>
</form>

<script>
	
	$("#formSignIn").validate({
	      rules: {
	         "email":{
	            "required": true,
	            "email": true
	         },
	         "password":{
		        "required": true,
			 }
	      }
	  });
	  
</script>
